#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bunx commitlint --edit "$1" || exit 1

message="$(cat "$1")"

bun scripts/bump-version.ts "$message" || exit 1

git add package.json
git add bun.lockb
